services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: angularfrontend
    build:
      context: ./AngularFrontend
      dockerfile: ./Dockerfile
    restart: always
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    depends_on:
      - backend
      - frontend
      - certbot
  backend:
    container_name: nodebackend
    build:
      context: ./NodeBackend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres
    image: postgres:14
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    restart: always
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/log:/var/log/letsencrypt:rw
    environment:
      - DOMAIN=opsforall.net
      - EMAIL=karimmaroous@gmail.com
    restart: unless-stopped

  # certbot-renew:
  #   image: certbot/certbot:latest
  #   container_name: certbot-renew
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   command: renew --quiet --webroot --webroot-path /var/www/certbot
  #   restart: unless-stopped