provider: aws
aws: 
  region: us-east-1
  zoneType: public  
serviceAccount:
  create: true
  name: external-dns
  
rbac:
  create: true
  serviceAccountName: external-dns

domainFilters:
  - eksops.site

policy: sync
registry: txt 
txtOwnerId: ops-cluster

interval: 3m 
logLevel: debug

sources:
  - service
  - ingress