
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: monitoring
spec:
  secretName: prometheus-tls
  dnsNames:
  - prometheus.eksops.site
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - prometheus.eksops.site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
