apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-certificate
  namespace: argocd
spec:
  secretName: argocd-server-tls
  commonName: argocd.eksops.site
  dnsNames:
  - argocd.eksops.site
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - argocd.eksops.site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer