apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
  - grafana.eksops.site
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - grafana.eksops.site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
