
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: monitoring
spec:
  secretName: wildcard-tls
  dnsNames:
  - "*.eksops.site"
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - "*.eksops.site"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
