controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "vpc-id=vpc-0a1b2c3d4e5f6g7h8"
    
    ports:
      http: 80
      https: 443
    targetPorts:
      http: 80
      https: 443
    selector:
      app.kubernetes.io/name: ingress-nginx
  publishService: 
    enabled: true