controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: eksops.site
    
    ports:
      http: 80
      https: 443
    targetPorts:
      http: 80
      https: 443
    selector:
      app.kubernetes.io/name: ingress-nginx
  publishService: 
    enabled: true