grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /
      external-dns.alpha.kubernetes.io/hostname: grafana.eksops.site
    
    hosts:
      - grafana.eksops.site

    path: /

    tls: 
    - secretName: wildcard-tls
      hosts:
      - "*.eksops.site"

    # datasources:
    #   name: Prometheus
    #   uid: prometheus
    #   type: prometheus
    #   url: https://prometheus.eksops.site
    #   access: proxy 

prometheus:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /
      external-dns.alpha.kubernetes.io/hostname: prometheus.eksops.site

    hosts: 
    - prometheus.eksops.site
    paths: 
    - /

    tls: 
      - secretName: wildcard-tls
        hosts:
          - "*.example.com"

 