name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Set workspace or create if not exists'
        run: terraform workspace select default || terraform workspace new default
      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan -destroy'
        run: terraform plan

      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve